### ISSUE TITLE
All the steps are appearing in a corner 

### ISSUE THREAD

**Issue by Jagadeesz** [okgrow/react-native-copilot#14] opened 2018-01-31 11:23 UTC

**Comment by RichardLitt** [comment] 2018-01-31 14:51
Thanks @Jagadeesz. Can you explain a bit further? What do you mean by various places? Which corner? Do you have a screenshot you could share? And do you possibly have the code available so that we could look at it? 

Right now, this would be very tough to replicate. Hopefully we'll be able to figure out how to help you.

**Comment by mechabyte** [comment] 2018-02-02 16:13
Not the OP, but I've experienced a similar issue as well. 
<img width="545" alt="screen shot 2018-01-15 at 10 04 29 am" src="https://user-images.githubusercontent.com/1922389/35742812-4a1abcc8-0801-11e8-978a-147a36f3a435.png">. I don't have the code anymore as it was on a deleted branch, however I'd arranged it that the copilot would step would appear on a screen following login-- I believe it could've been an issue with React Navigation. Sorry I can't offer too much help, just wanted to chime in.

**Comment by mechabyte** [comment] 2018-02-02 16:15
In the screenshot, I'd selected the main content view (under navigation header) with a copilot wrapped view.

**Comment by RichardLitt** [comment] 2018-02-02 19:26
Thanks @mechabyte. I think let's close this one until we have code to look at - it's not easy to replicate at the moment with the information given. Let us know if you run into it again!

**Comment by mohebifar** [comment] 2018-03-16 16:24
@anti-nerd How are you creating your `walkthrouable` components? Is the component that you're trying to make `walkthrouable` a native component or one that you implemented yourself?

**Comment by anti-nerd** [comment] 2018-03-16 16:34
@mohebifar it's a custom component. Please have a look at the [Gist here](https://gist.github.com/anti-nerd/b6b3ca87416788856b2b4a5763997925). Maybe I'm just missing something very minor but I can't pinpoint what the issue is.

To see how I'm rendering the `walkthroughable` component, have a look at the `showCategoryFilters(CategoriesStep) ` function. The component `const CategoriesStep` itself is being called from the render function; I had to put it there because of how I'm handling state.

I'll appreciate any assistance because I need to get this to work urgently.

**Comment by mohebifar** [comment] 2018-03-28 14:24
It's a bit hard to reproduce for me. It'd be better if you could share a [snack](https://snack.expo.io/) and a runnable code.

**Comment by anti-nerd** [comment] 2018-04-02 14:09
Thanks for the feedback, @mohebifar. I'll work on this and share.

**Comment by anniewey** [comment] 2018-04-06 00:33
I'm having the same issue too, any fix for this yet?

**Comment by mohebifar** [comment] 2018-05-02 19:47
I refactored the code for measuring element sizes and rendering the modal in V2. Could you please test your code again with the latest version of the package (`2.1.0`)? @anniewey @anti-nerd @Jagadeesz

**Comment by mohebifar** [comment] 2018-08-28 15:59
Closing this for now. Feel free to re-open it if you are still seeing the issue.

**Closed by mohebifar** 2018-08-28 15:59 UTC
Labels: bug

**Comment by neel-simform** [comment] 2025-01-07 20:13
Hello @mohebifar
Tooltips occasionally appear in the corner, as mentioned in this thread.

@anniewey, @crim3hound, @mechabyte Do you have a solution for this? I'm facing the same issue where it sometimes opens from the corner.

It seems like the collaborators are not actively addressing the issues.

**Comment by crim3hound** [comment] 2025-06-25 23:39
@neel-simform, sorry for the late reply - I'm just seeing your mention. Unfortunately, I haven't worked on this app in many years, so from my end, I don't have any current updates to offer for a resolution to the issue.
